### PR TITLE
Fix #87: Do not break when no outputFile is set

### LINKED ISSUE #87: Error if no outputFile defined (regression in v0.4.0)
Recent commit d5dc8081409f467d125cfdb149b1a1a61b1f0a4a causes karma-junit-reporter to no longer function if an `outputFile` is not defined in the config, even though `outputFile` is documented as optional and was previously optional. The error is `TypeError: Cannot read property 'charAt' of undefined`, and it's caused by calling `pathIsAbsolute(outputFile)` in `writeXmlForBrowser` without first checking to make sure `outputFile` was set.

### PR DESCRIPTION
**Pull request by matthauck**

### CODE REVIEW

**Comment by matthauck** [comment]
Doh. Didn't realize you guys had a CLA to sign. I'll have to get back to you on that...

**Comment by vermeeca** [comment]
I was the submitter of the PR that introduced this, so I already have a CLA signed.  If it helps, I just submitted https://github.com/karma-runner/karma-junit-reporter/pull/89 which is essentially the same fix.

If my PR helps get things resolved sooner, great.

**Comment by dignifiedquire** [comment]
Thanks @vermeeca and @matthauck closing in favor of #89

**Comment by matthauck** [comment]
:+1:

On Monday, March 21, 2016, Friedel Ziegelmayer <notifications@github.com>
wrote:

> Closed #88 <https://github.com/karma-runner/karma-junit-reporter/pull/88>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/karma-runner/karma-junit-reporter/pull/88#event-597283883>
>


-- 
Matt

**Pull request closed without merging**
