### PR TITLE
Allow user to specify filename

### PR DESCRIPTION
**Pull request by SimenB**

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks, could you please add some documentation for this and change the commit message to follow our convention.

**Comment by SimenB** [comment]
@Dignifiedquire Changed the commit-message. There already is a small change to the readme to indicate this. Does it need more?

**Comment by Dignifiedquire** [comment]
Ups, missed that somehow.

Thanks :octocat:

**Comment by Dignifiedquire** [comment]
Published as `0.3.2`

**Pull request merged**
