### PR TITLE
fix the not existing browser directory issue

### PR DESCRIPTION
**Pull request by killercentury**
These changes should fix karma-runner/karma-junit-reporter#48

### CODE REVIEW

**Comment by killercentury** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
Thanks, could you change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html) please?

**Comment by killercentury** [comment]
@Dignifiedquire I have changed the commit message. Hope it is OK.

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Comment by Dignifiedquire** [comment]
Released as `0.3.3`

**Pull request merged**
