### PR TITLE
Initialize var suites early

### PR DESCRIPTION
**Pull request by randakar**
As https://github.com/karma-runner/karma-junit-reporter/issues/61#issuecomment-264468229
Minor cleanup. Doing it this way should be faster though (no constructor call overhead, less code to begin with).

Credit goes to https://github.com/robinj for this one. I just implemented it.

### CODE REVIEW

**Comment by randakar** [comment]
I signed it.

**Comment by dignifiedquire** [comment]
Are you sure you can remove the init from `run_start`? This way if there are multiple runs it does not get reset

**Comment by dignifiedquire** [comment]
I'm especially thinking about runs with `autoWatch: true`

**Comment by randakar** [comment]
The reset is exactly what was causing issues. In some cases the onRunComplete() event would reset the suites object (set it to null) and then a different run (that was running simultaneously) would access it. Kaboom.

See the commit merged to the tip of master - there's a reason that is done.
I have made a second pull request that nulls the individual suite stored in the suites object when the run ends. That way memory is still cleared after each run (hopefully preventing a massive leak).

**Comment by dignifiedquire** [comment]
Thanks :octocat:

**Comment by randakar** [comment]
As an aside, I'm pretty sure a casual look at other reporters would show a repeat of this exact same pattern.

The only one I have in our builds is the Jenkins reporter, and that one does this:

  this.onRunStart = function(browsers) {
    suites = Object.create(null);
    xml = builder.create('testsuites');
---

So there's probably an opportunity there for further patches.

**Pull request merged**
