### PR TITLE
fix: Add back `outputFile` config

### LINKED ISSUE #58: outputFile dropped in v0.3.4 - related to Jenkins CI integration
Reading the Karma Runner v0.13 doc to integrate with [Jenkins CI](https://karma-runner.github.io/0.13/plus/jenkins.html), there indicates to use `outputFile`

But in the last version (0.3.4 [index.js](https://github.com/karma-runner/karma-junit-reporter/blob/v0.3.4/index.js)) I don't found this support in the code, until 0.3.3 in the [index.js was loaded in line 10](https://github.com/karma-runner/karma-junit-reporter/blob/v0.3.3/index.js#L10) and used inside  [writeXmlForBrowser function](https://github.com/karma-runner/karma-junit-reporter/blob/v0.3.3/index.js#L40-L48)

--

for now to generate report to Jenkins CI I'm using [v0.2.2](https://github.com/karma-runner/karma-junit-reporter/tree/v0.2.2) and [Jenkins CI config from Karma Runner v0.12](https://karma-runner.github.io/0.12/plus/jenkins.html)

```javascript
...
    // test results reporter to use
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['junit', 'coverage'],

    // https://karma-runner.github.io/0.12/plus/jenkins.html
    // https://github.com/karma-runner/karma-junit-reporter
    junitReporter: {
      outputFile: 'tests_out/junit/test-results.xml'
    },

    // https://github.com/karma-runner/karma-coverage
    // https://github.com/yahoo/istanbul

    // optionally, configure the reporter
    coverageReporter: {
      type : 'lcovonly', // produces an lcov.info file
      dir : 'tests_out/coverage/',
      subdir: '.'
    },
...
```

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Closes #58

### CODE REVIEW

**Comment by evandavis** [comment]
Why does this automatically nest inside a `$browser` folder?

**Comment by Dignifiedquire** [comment]
> Why does this automatically nest inside a $browser folder?

Because that was the previous behaviour, which I'm trying to restore

**Comment by SimenB** [comment]
If this restores old behavior, why is it not merged? You broke backwards compatibility in a patch release. Please revert and bump minor (as you're still on 0.x.x (why isn't Karma and it's plugins on 1.x btw?)) with this new behavior if it's still wanted.

For us nesting is fine, as we do `**/test-results.xml`.

Fix for now is of course just to revert to `0.3.3`, but that shouldn't be necessary IMO.

**Comment by TheSavior** [comment]
@Dignifiedquire bump.

**Comment by Dignifiedquire** [comment]
Merging, to restore old behaviour.

**Pull request merged**
