### PR TITLE
Fixing spelling of initialize

### PR DESCRIPTION
**Pull request by dschaller**

### CODE REVIEW

**Comment by dschaller** [comment]
I signed it!

**Comment by dschaller** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
Thanks can you please change the commit to follow our convention?  sth like`style: Fix typo in jnitialize`

**Comment by dschaller** [comment]
:+1: @dignifiedquire amended the commit message to the proper format

**Comment by dignifiedquire** [comment]
Thanks

**Pull request merged**
