### PR TITLE
fix: restore suite in classname for old XML

### LINKED ISSUE #179: Suite (package) name is not prepended to the classname attribute in the testcase element
If you set the `suite` property in the config, then this value is not prepended to the classname attribute in the testcase element.

https://github.com/karma-runner/karma-junit-reporter/blob/2f43e5063e050b7853ebcc82c24ecc26310e0cff/index.js#L144

This line should probably be:
`name += pkgName + '.'`

Currently the workaround is to use the `classNameFormatter` function to customize the classname attribute.

### PR DESCRIPTION
**Pull request by jason-ha**
Fix #179 
@jpaulin @dignifiedquire

### CODE REVIEW

**Review by jpaulin — APPROVED** [review]
Yep, definitely a bug in my original code.

**Review by jpaulin — APPROVED** [review]

**Comment by jason-ha** [comment]
@googlebot I signed it!

**Comment by jason-ha** [comment]
@jpaulin Is there someone you can recommend I ping to finish this up? Thanks

**Comment by jpaulin** [comment]
@dignifiedquire Hi, ping, do you happen to know anyone who's got rights to merge PRs into master in Karma's karma-junit-reporter? I'm kind of also left in the chasm of couple of years in between. This PR here is about a small one bug fix. This PR fixes
a bug that caused inaccurate reporting to Sonar. Thanks! /J

**Review by joeyparrish — APPROVED** [review]

**Comment by joeyparrish** [comment]
I apologize this project is not better maintained.  I was granted write access, but I don't have a lot of experience in this project and I am also not actively maintaining it.

**Comment by jason-ha** [comment]
Thanks @joeyparrish. Just happy to have the fix in.

**Comment by jason-ha** [comment]
@joeyparrish One more request. Can you create a release? (I thought there was one since releases say latest release in Oct 7., but then I notice that year is 2019. So we need one for this year.) Thanks.

**Pull request merged**
