### PR TITLE
Don't die if browser didn't start

### PR DESCRIPTION
**Pull request by robrich**
Very similar to https://github.com/karma-runner/karma-junit-reporter/issues/20

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks a lot, could you change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html) please?

**Comment by robrichnsons** [comment]
How's that?

**Comment by robrich** [comment]
How's that?

**Comment by Dignifiedquire** [comment]
Perfect, thanks :octocat:

**Pull request merged**
