### PR TITLE
Add support for additional properties to add to the report section

### PR DESCRIPTION
**Pull request by mikeng13**
This is useful for adding additional metadata from the build environment when producing the test report.

### CODE REVIEW

**Comment by mikeng13** [comment]
I signed it!

**Comment by mikeng13** [comment]
Any feedback on this @dignifiedquire ?

**Comment by dignifiedquire** [comment]
Looks good to me, can you please squash the commits into one and change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html)

**Comment by mikeng13** [comment]
@dignifiedquire I have squashed the commits and changed the message to match the convention. Let me know if it looks good!

**Comment by dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
