### PR TITLE
updating documentation with info about the suite argument

### PR DESCRIPTION
**Pull request by alexander-alvarez**
Saves the 5 seconds of effort that it takes to (ctrl-F in index.js)

### CODE REVIEW

**Comment by alexander-alvarez** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
Thanks, could you please update the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html)

**Comment by alexander-alvarez** [comment]
Sorry I missed that. Updated.

**Comment by Dignifiedquire** [comment]
Thanks, seems there are now two commits, could you try [squashing](http://davidwalsh.name/squash-commits-git) them together?

**Comment by alexander-alvarez** [comment]
take 3.

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
