### PR TITLE
Write skipped count in testsuite element

### PR DESCRIPTION
**Pull request by splintor**
https://github.com/karma-runner/karma-junit-reporter/issues/43

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks, can you please rebase onto the latest master and, change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html)

**Comment by webnard** [comment]
@dignifiedquire What's the status on this?

**Comment by splintor** [comment]
I didn't have time to look into it and rease. Feel free to apply my commit over the latest master and send a pull request.

**Comment by mdasberg** [comment]
Can anybody merge this?

**Comment by MarkRx** [comment]
What is the status on this?

**Comment by maryiam** [comment]
Please merge this Pull request

**Comment by splintor** [comment]
I'm the OP, and I no longer work on this issue. If someone wants, they can take it from here or issue a new PR, but if it waits for my feedback, it will probably not happen anytime soon.

**Pull request closed without merging**
